# ref: https://github.com/binokochumolvarghese/lightbi-hugo/blob/main/exampleSite/hugo.toml
baseURL = 'https://danuts-thegreat.github.io/blogfood/'
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "BlogFood"
theme = "ananke"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
description="Your can add your website description here."
previewCardImagePlacement = "bottom"

[frontmatter]
  date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
  expiryDate = ['expirydate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
  publishDate = ['publishdate', 'pubdate', 'published', 'date']

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

#[Params.Author]
#  name = "Danuts"
#  website = "https://danuts-thegreat.github.io/blogfood/"
#  authorInfo = "I'm a happy going spirit from Cloud Cuckoo Land!"
#  authorPostImage = "/img/unikitty.png"

[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/blog/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
